---
- hosts: webservers
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: Loome public_html kataloog userile
      file:
       path=/home/user/public_html
       owner=user
       group=user
       mode=0755
       state=directory

    - name: Lubame userdir mod
      apache2_module: name=userdir state=present
      

    - name: Kopeerime index.html rshaansible
      fetch: src=/var/www/html/index.html dest=./index.html flat=yes

    - name: Kopeerime userile index.html
      copy:
        src: ./index.html
        dest: /home/user/public_html/
        owner: user
        group: user
        mode: '0644'


    - name: user index.html redigeerimine
      lineinfile: dest=/home/user/public_html/index.html regexp="Apache2 Debian Default Page" line="Useri lehekylg"$

    - name: Alglaadimine Apache2
      service:
        name: apache2
        state: restarted



